### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SjogrenDev** [OutwalkStudios/discord-backup#18]
Hello,

I'd like to propose an enhancement to our guild backup system. When a saved message originates from the client user, it would be beneficial to send it as the client user rather than through a webhook. Additionally, I suggest implementing a feature to save message components for all messages, particularly those containing buttons with links, as they can be transmitted via webhooks.

Furthermore, for messages with components sent by the client user, it would be great to save all components for the ability to restore the entire message with its components.

**Comment by jleeson** [comment]
Hi @SjogrenDev! Unfortunately we cant sent the messages as the user themselves, Discord does not provide programmatic access to take action on a users behalf and at the time of server restoration, there is no guarantee the user is in the server or even exists anymore. The closest we can get is sending the message on a webhook with the name and icon swapped to match the user who sent it, which is how this package currently works.

It does look like its possible for this package to support saving and restoring message components that don't require a bot to handle the interaction which likely is only the link buttons as you mentioned. I don't currently have the time to implement this, but if you would like to submit a PR for it, I would be happy to merge and release it. It would require changing the `fetchChannelMessages` function in `utils.js`

**Comment by SjogrenDev** [comment]
Hi, I’m referring to the client user. (Bot itself) not other Discord users,
so the messages owned by the bot loading the backup would send its own
messages. Sure, I’ll look into your repo and get back to you.

**Comment by jleeson** [comment]
Oh I see what you mean now, my bad. Its been a while since I have worked with this package but I will take a look at this. This package ideally works independently of the bot itself, only requiring the guild to be passed in, but this could be done by providing the client object to the function and falling back to the webhook when its not provided. If you want to include this in your PR if you add the message component support you can, otherwise I will add this next time I get the chance to work on this package.

**Comment by SjogrenDev** [comment]
Hi,

I've created a PR. I've tested it in different scenarios and seems like webhooks support all components not just the link buttons (Discord.ButtonStyle.Link).
