### ISSUE TITLE
New feature: Automatically assigning roles again

### ISSUE THREAD

**Issue by TimWelm** [OutwalkStudios/discord-backup#6]
Maybe a nice addition to this package could be that it would automatically assign the users their old roles again after the roles have been restored.

**Comment by jleeson** [comment]
Hey @TimWelm, I currently don't have time to work on a new feature like this, but am open to any PRs for it.
This feature could be useful, I believe the package would need to be updated to properly backup members with their role information and invite them to the new server, upon them joining it could restore the roles they had previously assigned, this behavior would then need to be toggled via a restore option.

This is something I am happy to look into once I have more time, otherwise I have no problem merging a PR with this implemented.

**Comment by TimWelm** [comment]
I can maybe look into this at some point, I am currently busy as well but I'd be happy to help you where I can!

**Comment by jleeson** [comment]
@TimWelm This package now supports restoring roles for members that have been backed up in v0.5.0. all thats needed is to enable the `backupMembers` option in the `backup.create` function and by default any roles they had will be reassigned to them if they are in the server while its being restored.
